# Generated by Django 4.1.7 on 2023-03-18 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_address', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_contact', models.IntegerField(blank=True, max_length=10, null=True)),
                ('stock_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('costing', models.CharField(blank=True, max_length=20, null=True)),
                ('is_available', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parts_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(default=False, max_length=200)),
                ('working_status', models.CharField(default=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=False, max_length=200)),
                ('project_pricing', models.CharField(default=False, max_length=200)),
                ('working_status', models.CharField(default=False, max_length=200)),
                ('project_description', models.CharField(default=False, max_length=200)),
                ('project_inventory', models.IntegerField(default=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ManyToManyField(blank=True, default=None, null=True, related_name='Inventory_db', to='account.inventory_db')),
            ],
        ),
        migrations.CreateModel(
            name='Task_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_quantity', models.IntegerField(default=False, max_length=200)),
                ('opretions', models.CharField(default=False, max_length=200)),
                ('working_status', models.CharField(default=False, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.parts_db')),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project_db')),
            ],
        ),
        migrations.CreateModel(
            name='Transporter_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.IntegerField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_for_the_day', models.CharField(default=False, max_length=200)),
                ('check_in', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.BooleanField(default=False)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parts_id', models.ManyToManyField(blank=True, default=None, null=True, related_name='parts_db', to='account.parts_db')),
                ('projet_id', models.ManyToManyField(blank=True, default=None, null=True, related_name='project_id', to='account.project_db')),
                ('task_id', models.ManyToManyField(blank=True, default=None, null=True, related_name='task_db', to='account.task_db')),
            ],
        ),
        migrations.AddField(
            model_name='parts_db',
            name='projet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project_db'),
        ),
    ]
