# Generated by Django 4.1.7 on 2023-03-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_leave_application_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application_db',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
