# Generated by Django 4.1.7 on 2023-03-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_leave_application_db_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_db',
            name='part_description',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
