# Generated by Django 4.1.7 on 2023-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_parts_db_part_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_db',
            name='working_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
