# Generated by Django 4.1.7 on 2023-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_parts_db_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_db',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
