# Generated by Django 4.1.7 on 2023-04-06 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_parts_db_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdate_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_status', models.CharField(blank=True, max_length=200, null=True)),
                ('part_description', models.CharField(default=False, max_length=200)),
                ('total_hours', models.CharField(default=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.parts_db')),
                ('projet_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.project_db')),
                ('task_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.task_db')),
            ],
        ),
    ]
