# Generated by Django 4.1.7 on 2023-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userupdate_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='is_updated',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
