# Generated by Django 4.1.7 on 2023-05-22 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_address_user_emergency_no_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_db',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 22, 6, 9, 25, 601586, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
