# Generated by Django 4.1.7 on 2023-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_inventory_db_costing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_db',
            name='costing',
            field=models.CharField(default='svdt', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='inventory_name',
            field=models.CharField(default='svdt', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='is_available',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='stock_quantity',
            field=models.CharField(default='svdt', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='supplier_address',
            field=models.CharField(default='svdt', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='supplier_contact',
            field=models.CharField(default='svdt', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='supplier_name',
            field=models.CharField(default='svdt', max_length=100),
        ),
    ]
