# Generated by Django 4.1.7 on 2023-05-24 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_inventory_db_costing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_db',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 24, 6, 24, 7, 879906, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory_db',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
