# Generated by Django 4.1.7 on 2023-05-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_inventory_db_created_at_inventory_db_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Subadmin', 'Subadmin'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
