# Generated by Django 4.1.7 on 2023-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_project_db_project_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='part_doc',
            field=models.FileField(blank=True, null=True, upload_to='part_dox/'),
        ),
    ]
