# Generated by Django 4.1.7 on 2023-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_task_db_part_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupdate_db',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userupdate_db',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userupdate_db',
            name='task_img',
            field=models.ImageField(blank=True, null=True, upload_to='taskimages/'),
        ),
    ]
