# Generated by Django 4.2.1 on 2023-05-31 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_remove_project_db_project_doc_project_img_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_img_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_doc', models.FileField(blank=True, null=True, upload_to='part_doc/')),
                ('part_img', models.ImageField(blank=True, null=True, upload_to='part_img/')),
                ('part_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.parts_db')),
            ],
        ),
    ]
