# Generated by Django 4.2.1 on 2023-06-01 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_project_img_doc_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_img_doc',
            name='part_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_img_docs', to='account.parts_db'),
        ),
    ]
