# Generated by Django 4.2.1 on 2023-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_part_img_doc_part_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_db',
            name='estimation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
