# Generated by Django 4.2.1 on 2023-06-01 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_project_db_estimation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_db',
            name='emp',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
