# Generated by Django 4.2.1 on 2023-06-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_project_db_project_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_db',
            old_name='inventory',
            new_name='secondary_inventory',
        ),
        migrations.RemoveField(
            model_name='inventory_db',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='inventory_db',
            name='supplier_address',
        ),
        migrations.RemoveField(
            model_name='inventory_db',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='inventory_db',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='costing',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='inventory_name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='stock_quantity',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.CreateModel(
            name='secondary_inventory_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.CharField(default=False, max_length=100)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_inventory_stock', to='account.project_db')),
                ('secondary_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_inventory', to='account.inventory_db')),
            ],
        ),
    ]
