# Generated by Django 4.2.1 on 2023-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_customer_db_supplier_db_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts_db',
            old_name='projet_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='task_db',
            old_name='projet_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='timesheet_db',
            old_name='projet_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='userupdate_db',
            old_name='projet_name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='parts_db',
            name='part_doc',
            field=models.FileField(blank=True, null=True, upload_to='part_doc/'),
        ),
        migrations.AlterField(
            model_name='parts_db',
            name='part_description',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='project_db',
            name='project_description',
            field=models.TextField(default=False),
        ),
    ]
