# Generated by Django 4.2.1 on 2023-06-09 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_rename_projet_id_parts_db_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_img_doc',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='parts_db',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Part_img_doc',
        ),
        migrations.DeleteModel(
            name='Project_img_doc',
        ),
        migrations.AddField(
            model_name='parts_db',
            name='emp_id',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
