# Generated by Django 4.2.1 on 2023-06-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_remove_project_img_doc_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_db',
            name='part_doc',
        ),
        migrations.RemoveField(
            model_name='task_db',
            name='parts_quantity',
        ),
    ]
