# Generated by Django 4.2.1 on 2023-06-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_remove_task_db_part_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet_db',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='timesheet_db',
            name='parts_id',
        ),
        migrations.RemoveField(
            model_name='timesheet_db',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='timesheet_db',
            name='task_id',
        ),
        migrations.DeleteModel(
            name='Leave_application_db',
        ),
        migrations.DeleteModel(
            name='Timesheet_db',
        ),
    ]
