# Generated by Django 4.2.1 on 2023-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_remove_timesheet_db_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='is_poverty',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Hedium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
    ]
