# Generated by Django 4.2.1 on 2023-06-12 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_task_db_is_updated_task_db_is_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_db',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
