# Generated by Django 4.2.1 on 2023-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_task_db_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='is_task',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
